version: "3.7"
services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: yvanne22/hello-laravel:1.0.1
    container_name: hello-world
    restart: unless-stopped
    working_dir: /var/www/
    networks:
      - laravel-app

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel-app

networks:
  laravel-app:
    driver: bridge