apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-laravel
  labels:
    app: hello-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-laravel
  template:
    metadata:
      labels:
        app: hello-laravel
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: app
          image: yvanne22/hello-laravel:1.0.1
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        linkerd.io/inject: enabled
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: default.conf
                path: default.conf
        - name: index
          configMap:
            name: index
            items:
              - key: index.php
                path: index.php
      containers:
        - name: nginx
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: index
              mountPath: /var/www/public
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
