apiVersion: v1
kind: Service
metadata:
  name: hello-laravel
spec:
  selector:
    app: hello-laravel
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80